// Vite 配置：把地图编辑器的「保存场景 / 模型上传」接口挂到与页面同源（5173）。
// 这样编辑器读写场景、导入模型都不做跨域请求，也无需单独运行 8080 服务。
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const MODELS_DIR = path.join(root, 'public', 'models'); // 模型集中目录
const MAX_UPLOAD = 64 * 1024 * 1024; // 单次上传上限 64MB

export default {
  // 相对 base：构建产物的入口/JS/CSS 用相对路径引用，适配 GitHub Pages 根目录或子路径部署
  base: './',
  server: { port: 5173 },
  build: {
    rollupOptions: {
      input: {
        index: path.join(root, 'index.html'),
        editor: path.join(root, 'editor.html'),
      },
    },
  },
  plugins: [
    {
      name: 'map-editor-api',
      configureServer(server) {
        server.middlewares.use((req, res, next) => {
          const url = (req.url || '').split('?')[0];

          // 保存场景：改写游戏的源码数据模块 editorMapData.js，并同步写 editor-scene.json
          if (req.method === 'POST' && url === '/api/scene') {
            let body = '';
            req.on('data', (c) => { body += c; });
            req.on('end', () => {
              try {
                const data = JSON.parse(body);
                // 编辑器 serialize() 输出对象 { scenery:[...], placed:[...] }，需原样写盘（兼容旧纯数组格式）
                const payload = Array.isArray(data) ? data : data;
                const src =
                  '// AUTO-GENERATED by the map editor (editor.html「保存场景」). Do not edit by hand.\n' +
                  '// 游戏通过 src/world/EditorBuildings.js 直接 import 这份数据渲染建筑。\n' +
                  'export const editorMapData = ' +
                  JSON.stringify(payload, null, 2) +
                  ';\n';
                fs.writeFileSync(path.join(root, 'src', 'world', 'editorMapData.js'), src, 'utf8');
                fs.writeFileSync(path.join(root, 'public', 'assets', 'editor-scene.json'), JSON.stringify(payload, null, 2));
                res.setHeader('Content-Type', 'application/json');
                res.end(JSON.stringify({ ok: true, count: Array.isArray(data) ? data.length : Object.keys(payload).length }));
              } catch (e) {
                res.statusCode = 400;
                res.setHeader('Content-Type', 'application/json');
                res.end(JSON.stringify({ ok: false, error: String(e) }));
              }
            });
            return;
          }

          // 模型清单：读取 public/models 目录下所有 .glb，供素材库使用
          if (req.method === 'GET' && url === '/api/models') {
            try {
              let names = [];
              if (fs.existsSync(MODELS_DIR)) {
                names = fs.readdirSync(MODELS_DIR).filter((n) => n.toLowerCase().endsWith('.glb')).sort();
              }
              const items = names.map((n) => ({ name: n.replace(/\.glb$/i, ''), url: '/models/' + n }));
              res.setHeader('Content-Type', 'application/json');
              res.end(JSON.stringify({ ok: true, items }));
            } catch (e) {
              res.statusCode = 500;
              res.setHeader('Content-Type', 'application/json');
              res.end(JSON.stringify({ ok: false, error: String(e) }));
            }
            return;
          }

          // 模型上传：原样写入 public/models/，返回统一绝对路径 /models/xxx.glb
          if (req.method === 'POST' && url === '/api/upload') {
            const name = (req.headers['x-filename'] || 'import.glb').replace(/[^a-zA-Z0-9._-]/g, '_');
            const saved = 'import-' + Date.now() + '-' + name;
            const chunks = [];
            let total = 0;
            req.on('data', (c) => { total += c.length; if (total > MAX_UPLOAD) req.destroy(); chunks.push(c); });
            req.on('end', () => {
              try {
                fs.writeFileSync(path.join(MODELS_DIR, saved), Buffer.concat(chunks));
                res.setHeader('Content-Type', 'application/json');
                res.end(JSON.stringify({ ok: true, url: '/models/' + saved }));
              } catch (e) {
                res.statusCode = 500;
                res.setHeader('Content-Type', 'application/json');
                res.end(JSON.stringify({ ok: false, error: String(e) }));
              }
            });
            return;
          }

          next();
        });
      },
    },
  ],
};