// AUTO-GENERATED by the map editor (editor.html「保存场景」). Do not edit by hand.
// 游戏通过 src/world/EditorBuildings.js 直接 import 这份数据渲染建筑。
export const editorMapData = {
  "scenery": [
    {
      "key": 0,
      "x": 0,
      "y": 0,
      "z": 0,
      "rotY": 0,
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      }
    }
  ],
  "placed": [
    {
      "kind": "builtin",
      "url": "/models/军中.glb",
      "x": 3.089283648025914,
      "y": -0.005187274445469736,
      "z": 147.0276094216756,
      "rotY": -1.5707963267948966,
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "collider": {
        "enabled": false,
        "hx": 5.795568823814392,
        "hy": 6.0845299230847125,
        "hz": 22.12237359185577,
        "oy": 6.900921152714229
      }
    },
    {
      "kind": "builtin",
      "url": "/models/未命名.glb",
      "x": 0.8125212428807203,
      "y": 0,
      "z": 118.39929358987189,
      "rotY": 1.5707963267948966,
      "scale": {
        "x": 1.2488275936464095,
        "y": 1,
        "z": 3.676211624339331
      },
      "collider": {
        "enabled": true,
        "hx": 63,
        "hy": 1,
        "hz": 20,
        "oy": 0
      }
    },
    {
      "kind": "builtin",
      "name": "building-small-a",
      "url": "/assets/building-small-a.glb",
      "x": 2,
      "y": 0.604455241260478,
      "z": 179,
      "rotY": 3.141592653589793,
      "scale": {
        "x": 23.41270573329628,
        "y": 19.88824653111537,
        "z": 16.945354384231287
      },
      "collider": {
        "enabled": true,
        "hx": 0.5,
        "hy": 0.4749999940395355,
        "hz": 0.5,
        "oy": 0.4749999940395355
      }
    },
    {
      "kind": "builtin",
      "url": "/models/building-small-b.glb",
      "x": -32.19209347314544,
      "y": 0.7607891501089838,
      "z": 180,
      "rotY": 3.141592653589793,
      "scale": {
        "x": 50.44036128503923,
        "y": 13.902463514945897,
        "z": 34.855199095342556
      },
      "collider": {
        "enabled": true,
        "hx": 0.5,
        "hy": 0.813249945640564,
        "hz": 0.5,
        "oy": 0.813249945640564
      }
    }
  ]
};
